### ISSUE TITLE
Sort the info-list

### ISSUE THREAD

**Issue by sara-02** [sara-02/awesome-infograhics#2]
Sort list for easier search to prevent duplication.

**Comment by antiDigest** [comment]
You have not yet accepted any of my pull requests. Majra kya hai ?

**Comment by sara-02** [comment]
@evamy So how I can was `watching` the repo, due to which I missed the notifications. 
Well, I have 2 of your requests. Kindly resolve the final one and we should be good to merge that bit as well.

**Comment by sara-02** [comment]
Resolved by #5
